C  THIS VERSION: 14/08/1991 AT 12:05:02 PM.
CS    BLOCK DATA SDATAL
CD    BLOCK DATA DDATAL
C
C  DEFINE INITIAL VALUES FOR COMMON VARIABLES
C  FOR THE SUBROUTINE AUGLG VIA BLOCK DATA.
C
C  NICK GOULD, 15TH MARCH 1990
C  FOR CGT PRODUCTIONS.
C
CS    REAL             RMU, RMUTOL, FIRSTC, FIRSTG
CD    DOUBLE PRECISION RMU, RMUTOL, FIRSTC, FIRSTG
      LOGICAL          NEWSOL
CS    COMMON   / SCOMAL / RMU, RMUTOL, FIRSTC, FIRSTG, NEWSOL
CD    COMMON   / DCOMAL / RMU, RMUTOL, FIRSTC, FIRSTG, NEWSOL
CS    SAVE     / SCOMAL /
CD    SAVE     / DCOMAL /
CS    DATA       RMU   , RMUTOL / 1.0E-1, 1.0E-1 /
CD    DATA       RMU   , RMUTOL / 1.0D-1, 1.0D-1 /
CS    DATA       FIRSTG, FIRSTC / 1.0E-1, 1.0E-1 /
CD    DATA       FIRSTG, FIRSTC / 1.0D-1, 1.0D-1 /
      END
